pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

include ':FtcRobotController'
include ':TeamCode'
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
        maven {
            url = "https://mymaven.bylazar.com/releases"
        }
        maven {
            url = "https://repo.dairy.foundation/releases/"
        }
    }
}